### PR TITLE
Saving time of center of true signal in readout window time configuration

### PR DESCRIPTION
**Pull request by MyoungchulK**
If a user wants to know the location of the true signal (technically the center of true signal) inside the WF, the user needs to perform the below calculation themselves.

for (int m = 0; m < stations[i].strings[string_i].antennas[antenna_i].ray_sol_cnt; m++) {
.... double signal_center_offset = (double)(stations[i].strings[string_i].antennas[antenna_i].SignalBin[m] - stations[i].strings[string_i].antennas[antenna_i].time[0]) * settings1->TIMESTEP * 1.e9;
.... double signal_center_time = signal_center_offset + stations[i].strings[string_i].antennas[antenna_i].time_mimic[0];
.... **stations[i].strings[string_i].antennas[antenna_i].SignalBinTime.push_back(signal_center_time)**;
}

`for (int m = 0; m < stations[i].strings[string_i].antennas[antenna_i].ray_sol_cnt; m++)`: loop over each ray solution
`stations[i].strings[string_i].antennas[antenna_i].SignalBin[m]`: bin index of each ray's signal center in the long noise pad (length = `settings1->DATA_BIN_SIZE`)
`stations[i].strings[string_i].antennas[antenna_i].time[0]`: bin index of the beginning of the readout window (final output WF region) in the long noise pad
`settings1->TIMESTEP * 1.e9`: time width in nanosecond
`double signal_center_offset`: time offset between beginning of readout window and center of the signal
`stations[i].strings[string_i].antennas[antenna_i].time_mimic[0]`: time of the beginning of the readout window (final output WF region)
`double signal_center_time`: time of center of the signal based on readout window time config
`SignalBinTime`: the output array that stores signal center time

I decided to implement it inside the sim...

Let me know if you have a comment!

### CODE REVIEW

**Comment by clark2668** [comment]
Thanks Myoungchul, this is super super helpful. Can you add a few more words to the documentation (in a comment) about precisely what math you're doing here?

**Comment by MyoungchulK** [comment]
> Thanks Myoungchul, this is super super helpful. Can you add a few more words to the documentation (in a comment) about precisely what math you're doing here?

on it!:)

**Comment by MyoungchulK** [comment]
I updated it!

**Comment by MyoungchulK** [comment]
I will put this PR on hold.
After I added `vector<double> SignalBinTime;` in `Report.h`, I saw the below error if I tried to load AraOut.root made by the current version 
image

**Comment by MyoungchulK** [comment]
So.... the shenanigan is solved. It is ready to merge

**Comment by clark2668** [comment]
Weird. Go ahead tho!

**Pull request merged**
