### PR TITLE
Add PA to GetGain_1D_OutZero

### PR DESCRIPTION
**Pull request by abigailbishop**
When `GetGain_1D_OutZero` was modified to add the top/bottom VPols, it was only set up for the classic ARA stations. This PR adds the PA to this function assuming all PA Vpols use the bottom VPol gain and preserving the top/bottom pol assignments for the A5 antennas attached to the PA DAQ. 

I also noticed GetGain_1D is never used in AraSim so there is 1 commit removing GetGain_1D. 

(There are also many "merge pull request" commits from pulling the AraSim master branch into my main branch)

### CODE REVIEW

**Comment by abigailbishop** [comment]
Hey @jflaherty13 can I get your blessing on this? I want to make sure I didn't mess up the transmitter mode of AraSim. Thanks!

**Comment by FlahertyJustinC** [comment]
I'm getting consistent results with the Tx mode on both the main branch and this branch.  It's an error message, but it's the same for both cases and that's my problem to solve.

I hereby declare this pull request...

B L E S S E D

**Comment by abigailbishop** [comment]
Awesome thanks Justin!

**Comment by marcomuzio** [comment]
Thanks for fixing this Abby! It also looks good to me.

**Comment by abigailbishop** [comment]
Great thanks Marco! I'll merge this then :)

**Pull request merged**
