### PR TITLE
update the GetAngleAnt function

### LINKED ISSUE #36: antenna_phi calculation needs an update
The calculation of antenna_phi in the GetAngleAnt function is marked as "incorrect" and needs to be updated.

### PR DESCRIPTION
**Pull request by clark2668**
Update the GetAngleAnt function for a correct calculation of `antenna_theta` and `antenna_phi`. This fixes two things. 

First, GetAngleAnt was not calculating `antenna_phi` correctly.

Second, GetAngleAnt was calculating antenna_theta so that it indicated where the signal was  *going*. But `antenna_theta` needs to indicate where the signal *came from* in order to be used correctly in the new pol factor calculation (see above) and in the antenna gain calculation.

This bug would so far have not impacted AraSim sensitivity estimates because the antennas are approximately azimuthally and zenithally symmetric.

### CODE REVIEW

**Comment by MyoungchulK** [comment]
👍

**Comment by clark2668** [comment]
Okay, I'd like to get this merged back into AraSim. I ran a comparison of the latest in this branch (d9725c2) again a version of the trunk from a while ago (4108ec3). I chose this comparison specifically because it pre-dates the polarization calculation change (#31, 79a7fe3), which we know is sensitive to a bug in the phi calculation, which this PR fixes. See issue #36. 

As you can see in the plot, things look good at the veff level (differences are essentially within error bars). Are we good to merge? @toej93 ?

compare

**Comment by toej93** [comment]
Yea, go for it

**Comment by clark2668** [comment]
Great, thanks! I'll have to resolve that last conflict and then merge down.

**Pull request merged**
