### PR TITLE
Removed request to link to sqlite library (-lsqlite3) from Makefile a…

### PR DESCRIPTION
**Pull request by AndrewShultz**
…nd StandardDefinitions.mk. No include path for the sqlite headers is specified either, thus no need to link to the library.

### CODE REVIEW

**Comment by clark2668** [comment]
Looks great. I wonder why you couldn't do the merge yourself? Did you request review? I'll see if I can change that setting at some point...

**Comment by AndrewShultz** [comment]
I looked around a bit and couldn't find how to do it.  I'll try a bit
harder next time.

Andrew

**Comment by clark2668** [comment]
Okay, sounds good. I just don't see a reason to make you go through me every time haha :) Maybe you could have clicked "approve" yourself from the pull request page.... Try that next time maybe.

**Comment by clark2668** [comment]
Looking at it just a smidge more closely, it probably has something to do with the fact that you forked the repo instead of just having a branch (which is is totally fine!).

**Comment by AndrewShultz** [comment]
Could be. I didn't see an approve button. Or do I need to a submit for
review first?

Andrew

**Pull request merged**
