### PR TITLE
Adding antenna model wiki page link in Settings.h and the script for Chiba in-situ model in AraSim/data/antennas path

### PR DESCRIPTION
**Pull request by MyoungchulK**
Right now only `Settings.h` is changed.
I added a link for the [wiki page](http://ara.icecube.wisc.edu/wiki/index.php/Antenna_model)
I will add the script soon:)

### CODE REVIEW

**Review by toej93 — APPROVED** [review]
Looks good

**Comment by MyoungchulK** [comment]
Thanks! let me add script too in this merge

**Comment by MyoungchulK** [comment]
I added `In_situ_Model_maker.py` into `AraSim/data/antennas/` path.
If you run the code, It will generate these plots.

In_situ_Vpol_Model
In_situ_Hpol_Model

The code is including the fit values.
But It doesn't have a code that makes the model to the AraSim table format(.txt).

I'm currently excavating the format marker from our previous master's directory...
I think it will take some time. If there is no comment I want to merge this one first and I will make another merge request for the format maker:)

**Comment by clark2668** [comment]
This looks okay, go ahead and squash and merge!

**Pull request merged**
