### PR TITLE
Bug fixes and Primaries cleanup

### LINKED ISSUE #53: Remove hard coded path references to data folder
AraSim has hard coded path references to the `data` folder, for things like antenna patterns, etc. E.g. https://github.com/ara-software/AraSim/blob/master/Detector.cc#L1002

This is bad, and makes it impossible to run the AraSim executable, or anything that depends on the data folder, outside of the `AraSim` directory. We should remove it in favor of an environment variable like `ARASIM_DIR`.

### PR DESCRIPTION
**Pull request by marcomuzio**
I fixed a few bugs in Spectra and in IceModel & EarthModel that were causing issues with reading AraTrees outside the AraSim directory (this also precipitated the need for environmental variables to be defined in the AraSim tests). Also did a big clean up of the Primaries class (removed ~1000 lines from Primaries.cc and fixed formatting).

### CODE REVIEW

**Comment by clark2668** [comment]
Have you thought about adding something to AraSim.cc, where the first thing it does is check for the environment variable's existence, and fails out if it can't find it? At least check for existence, even better if it can check if it's pointed somewhere sensible...

**Comment by marcomuzio** [comment]
I can do that, does AraRoot do something like that by chance?

**Comment by clark2668** [comment]
No, I don't think so (though it probably should).

**Comment by marcomuzio** [comment]
Alright how's that look?

**Comment by clark2668** [comment]
I think this looks good. I guess you actually tested it and confirmed that when you don't set ARA_SIM_DIR these errors actually get thrown?

**Comment by marcomuzio** [comment]
Ya, that's right. I just set it to an empty string and the error was thrown.

**Comment by clark2668** [comment]
Awesome. Then I say merge away!

**Comment by clark2668** [comment]
Btw, I suspect this would address #53 ?

**Comment by marcomuzio** [comment]
Good call!

**Pull request merged**
